name: NatzSMP
main: com.natzdev.natzsmp.NatzSMP
version: 0.1.0
api-version: "1.21"
author: NatzSMP
softdepend:
  - PlaceholderAPI
  - Vault
  - LuckPerms

commands:
  natz:
    description: NatzSMP admin command
    usage: /natz <holo|npc|econ|level>
    permission: natz.admin

permissions:
  natz.admin:
    description: Allows use of /natz admin commands
    default: op
